name: mob3_uas_klp_02
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev



environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  google_generative_ai: ^0.4.3
  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  cloud_firestore: ^5.2.1
  connectivity_plus: ^6.0.5
  currency_text_input_formatter: ^2.2.3
  dio: ^5.4.3+1
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  fl_chart: ^0.69.2
  flutter_bloc: ^8.1.6
  flutter_slidable: ^3.1.1
  intl: ^0.19.0
  meta: ^1.12.0
  shared_preferences: ^2.3.2
  skeletonizer: ^1.4.2
  table_calendar: ^3.1.2
  uuid: ^4.5.0
  flutter_launcher_icons: ^0.14.2
  path_provider: ^2.1.5
  image_picker: ^1.1.2
flutter_launcher_icons:
  android: "launcher_icon"
  image_path_android: "assets/logo_app.png"
  image_path_ios: "assets/logo_app.png"
  ios: true
  min_sdk_android: 21
  
  # http: ^0.13.4

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
