// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_c4z0d6F5Q-cF9JpeeQqhz-qirpsBh40',
    appId: '1:357875289165:web:24817f54dd3ed994a16004',
    messagingSenderId: '357875289165',
    projectId: 'uangku-f36c6',
    authDomain: 'uangku-f36c6.firebaseapp.com',
    storageBucket: 'uangku-f36c6.firebasestorage.app',
    measurementId: 'G-0Y0LYZM9X9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhWboE-YLRkOvHHnQTF2u7pg7vU_hApGo',
    appId: '1:357875289165:android:343c053242afdfc2a16004',
    messagingSenderId: '357875289165',
    projectId: 'uangku-f36c6',
    storageBucket: 'uangku-f36c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV52-Aw-RgWajKKV-fzKn6uZcMShJUIcs',
    appId: '1:357875289165:ios:e7f804974dde6abfa16004',
    messagingSenderId: '357875289165',
    projectId: 'uangku-f36c6',
    storageBucket: 'uangku-f36c6.firebasestorage.app',
    iosBundleId: 'com.example.mob3UasKlp02',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV52-Aw-RgWajKKV-fzKn6uZcMShJUIcs',
    appId: '1:357875289165:ios:e7f804974dde6abfa16004',
    messagingSenderId: '357875289165',
    projectId: 'uangku-f36c6',
    storageBucket: 'uangku-f36c6.firebasestorage.app',
    iosBundleId: 'com.example.mob3UasKlp02',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_c4z0d6F5Q-cF9JpeeQqhz-qirpsBh40',
    appId: '1:357875289165:web:e1039ed6153d73c5a16004',
    messagingSenderId: '357875289165',
    projectId: 'uangku-f36c6',
    authDomain: 'uangku-f36c6.firebaseapp.com',
    storageBucket: 'uangku-f36c6.firebasestorage.app',
    measurementId: 'G-CB76GN2Q8F',
  );
}
